### ISSUE TITLE
dependency on symfony/console

### ISSUE THREAD

**Issue by lenada** [localheinz/github-changelog#41]
not stated in composer.json

```
PHP Fatal error:  Class 'Symfony\Component\Console\Application' not found in ...
```

**Comment by localheinz** [comment]
@lenada 

Thank you both for reporting and checking it out!

**Comment by localheinz** [comment]
@lenada 

Published a new release: https://packagist.org/packages/localheinz/github-changelog#0.1.3. Do you want to try again? There are issues, though, specifically #40. :sob:

**Comment by lenada** [comment]
@localheinz Thank you! `0.1.3` I can confirm it solves the missing symfony/console dependency.
