### ISSUE TITLE
SSL: certificate verification failed with github API

### ISSUE THREAD

**Issue by lenada** [localheinz/github-changelog#43]
I assume my php56 installed through brew just lacks proper ssl ca configuration, which is a pita ;)
I tried to play around with curl and openssl ini settings, pointing to ca-bundle.pems but gave up after a while.

I wonder how composer gets around this, do they ship their own ca bundle? or just don't use curl?

`[curl] 51: SSL: certificate verification failed (result: 5) [url] https://api.github.com/repos/localheinz`

**Comment by lenada** [comment]
seems to be a related/duplicate of https://github.com/guzzle/guzzle/issues/819

**Comment by localheinz** [comment]
@lenada 

I have no idea, to be honest - what happened there?

**Comment by lenada** [comment]
seems to be an os x (Mavericks) specific bug/feature.
trying github-changelog inside a linux vm works great :+1:  thank you @localheinz, @gianarb  this really simplifies collecting release notes

**Comment by localheinz** [comment]
Great you like it, @lenada!
